(()=>{"use strict";
const $=id=>document.getElementById(id),cv=$("c"),ctx=cv.getContext("2d",{alpha:false});let W=0,H=0,DPR=1,rotY=.6,rotX=.22,drag=null,spin=true,mode="discovery";
const P={surg:0,rt:0,tz:0,wk:12,mg:true};
const shells=[
 {r:[.46,.78,1.02],core:.42,harm:.02,inv:.04,k:[0,0,0]},
 {r:[.40,.66,.98],core:.46,harm:.08,inv:.10,k:[.18,.15,.28]},
 {r:[.34,.56,.95],core:.49,harm:.15,inv:.18,k:[.34,.28,.48]},
 {r:[.28,.48,.93],core:.52,harm:.24,inv:.27,k:[.48,.40,.61]},
 {r:[.24,.42,.96],core:.55,harm:.36,inv:.38,k:[.58,.49,.70]}
];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function size(){const r=$("abpFigure").getBoundingClientRect();DPR=Math.min(devicePixelRatio||1,1.4);W=Math.max(280,Math.round(r.width));H=Math.max(260,Math.round(r.height));cv.width=W*DPR;cv.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}
function level(){const a=Math.round((P.rt/84)*2),b=Math.round(P.tz*2),c=P.surg>.75?2:P.surg>.2?1:0,w=P.wk>18?1:0;return clamp(a+b+c+w,0,4)}
function state(){const q=shells[level()],mg=P.mg?0:1;return{rn:q.r[0]*(1+.10*mg),re:q.r[1]*(1+.08*mg),ri:q.r[2]*(1+.08*mg),necrosis:q.harm,invasion:q.inv,harm:q.harm,kR:q.k[0],kT:q.k[1]*(P.mg?1:.55),kC:q.k[2]*(P.mg?1:.72),surgEff:P.surg};}
function vol(r){return 4.18879*r*r*r}
function ground(){if(P.rt>72||P.tz>.88)return{k:'abs',t:'Insufficient support — abstain',e:'This public shell marks the requested region unsupported rather than extrapolating.'};if(!P.mg&&P.tz>.45)return{k:'unf',t:'Supported, historically unfavourable',e:'The selected context is shown as a supported but historically unfavourable demonstration state.'};if(P.rt>48&&P.tz>.55)return{k:'mix',t:'Supported, mixed response',e:'The selected combination is shown as a mixed-response demonstration state.'};if(P.surg>.02&&P.rt<20&&P.tz<.15)return{k:'fav',t:'Supported cytoreduction direction',e:'The public shell displays the supported cytoreduction route.'};return{k:'fav',t:'Supported, historically favourable',e:'The selected state is represented in the public demonstration envelope.'}}
const GC={base:'#6c8493',fav:'#2fe3d6',mix:'#ffb03a',unf:'#ff6b5e',abs:'#6c8493'};
function rad(th,z,seed,rough){return 1+rough*(.12*Math.sin(th*2+seed+z)+.07*Math.sin(th*5+1.7*z)+.04*Math.cos(th*7-seed))}
function shell(cx,cy,scale,r0,z,col,alpha,seed,rough,glow){ctx.beginPath();for(let i=0;i<=48;i++){const th=i/48*Math.PI*2,rr=r0*rad(th+rotY*.35,z,seed,rough),x=Math.cos(th)*rr,y=Math.sin(th)*rr*Math.cos(rotX),px=cx+x*scale,py=cy+y*scale-z*scale*Math.sin(rotX);i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.strokeStyle=col;ctx.globalAlpha=alpha;ctx.lineWidth=glow?1.35:.85;ctx.shadowColor=col;ctx.shadowBlur=glow?12:0;ctx.stroke();ctx.shadowBlur=0}
function draw(){const s=state(),gr=ground();ctx.globalAlpha=1;ctx.fillStyle='#03060b';ctx.fillRect(0,0,W,H);if(s.harm>.12){const hg=ctx.createRadialGradient(W*.53,H*.43,10,W*.53,H*.43,Math.max(W,H)*.55);hg.addColorStop(0,`rgba(255,60,40,${.16*s.harm})`);hg.addColorStop(1,'rgba(255,60,40,0)');ctx.fillStyle=hg;ctx.fillRect(0,0,W,H)}const g=ctx.createRadialGradient(W/2,H/2,10,W/2,H/2,Math.max(W,H)*.6);g.addColorStop(0,'rgba(20,44,60,.35)');g.addColorStop(1,'rgba(3,6,11,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='lighter';const cx=W*.53,cy=H*.43,sc=Math.min(W*.46,H*.46)/1.65;for(let i=0;i<24;i++){let z=-1+i/12;shell(cx,cy,sc,s.ri,z,'#9a6dff',.10,2,.75,false);shell(cx,cy,sc,s.re,z,'#2fe3d6',.16,1,.55,false);shell(cx,cy,sc,s.rn,z,s.necrosis>.2?'#ff6b50':'#ffb03a',.13,3,.45,false)}ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;shell(cx,cy,sc,s.ri,0,'#9a6dff',.9,2,.75,true);shell(cx,cy,sc,s.re,0,'#2fe3d6',1,1,.55,true);shell(cx,cy,sc,s.rn,0,s.necrosis>.2?'#ff6b50':'#ffb03a',1,3,.45,true);
const base={rn:.44,re:.78,ri:1},dN=(vol(s.rn)/vol(base.rn)-1)*100,dE=(vol(s.re)/vol(base.re)-1)*100,dI=(s.ri/base.ri-1)*100;$("mSurg").textContent=P.surg>.75?'HIGH':P.surg>.2?'PARTIAL':'NONE';$("mKr").textContent=Math.round(s.kR*100)+'%';$("mKt").textContent=Math.round(s.kT*100)+'%';$("mKc").textContent=Math.round(s.kC*100)+'%';$("mEnh").textContent=(s.re*100).toFixed(0)+'%';$("mInf").textContent=(s.ri*100).toFixed(0)+'%';$("mTot").textContent=Math.round((s.re+s.ri)*50)+'%';$("mRano").textContent=dE.toFixed(0)+'%';$("mCourse").textContent=dI.toFixed(0)+'%';$("mNec").textContent=Math.round(s.necrosis*100)+'%';$("mInv").textContent=Math.round(s.invasion*100)+'%';$("ground").style.borderColor=GC[gr.k];$("gT").textContent=gr.t;$("gE").textContent=gr.e;$("contrastLine").textContent=`Public visual shell · ${gr.t}. Controls select among coarse frozen demonstration states; production biological response operators and inverse-search logic are absent.`;updateMode(s,dN,dE,dI,gr)}
function updateMode(s,dN,dE,dI,gr){const eye=$("modeResultEye"),title=$("modeResultTitle"),txt=$("modeResultText"),pct=v=>(v>=0?'+':'')+v.toFixed(0)+'%';if(mode==='discovery'){eye.textContent='Discovery · target-directed interrogation';title.textContent=gr.t;$("r1l").textContent='Necrotic core';$("r1v").textContent=pct(dN);$("r2l").textContent='Enhancing rim';$("r2v").textContent=pct(dE);$("r3l").textContent='Infiltrative margin';$("r3v").textContent=pct(dI);txt.textContent=gr.e+' Unsupported regions remain unresolved.'}else if(mode==='design'){eye.textContent='Design · objective-conditioned comparison';title.textContent='Intervention designs produce different visible trade-offs.';$("r1l").textContent='Combined response';$("r1v").textContent=Math.round(s.kC*100)+'%';$("r2l").textContent='Enhancing volume';$("r2v").textContent=pct(dE);$("r3l").textContent='Treatment harm';$("r3v").textContent=Math.round(s.harm*100)+'%';txt.textContent='The public shell shows frozen trade-off states; protected search and ranking are not distributed.'}else{eye.textContent='Development · response modifiers';title.textContent='Biological context changes the displayed response state.';$("r1l").textContent='MGMT state';$("r1v").textContent=P.mg?'Methylated':'Unmethylated';$("r2l").textContent='Radiation necrosis';$("r2v").textContent=Math.round(s.necrosis*100)+'%';$("r3l").textContent='Induced invasion';$("r3v").textContent=Math.round(s.invasion*100)+'%';txt.textContent='This display is illustrative and not a production response operator.'}}
const supported={balanced:{mg1:[.55,42,.40,'Combined supported route'],mg0:[.55,34,.22,'Cytoreduction-led supported route']},rano:{mg1:[.90,56,.54,'Bulk-control supported route'],mg0:[.90,48,.26,'Bulk-control supported route']},inf:{mg1:[.55,24,.18,'Margin-preserving supported route'],mg0:[.55,18,.10,'Margin-preserving supported route']}};
function applySupported(){const obj=$("inverseObjective").value,x=supported[obj][P.mg?'mg1':'mg0'];P.surg=x[0];P.rt=x[1];P.tz=x[2];$("surg").value=String(x[0]);$("rt").value=x[1];$("tz").value=x[2];labels();$("bestRoute").textContent='ABP supported demonstration · '+x[3];$("bestLevels").textContent=`${surgName(x[0])} · radiation ${x[1]} Gy-eq · agent intensity ${x[2].toFixed(2)} · week ${P.wk}.`;$("globalOpt").textContent='withheld';$("supportedOpt").textContent=x[3];$("rankedRoutes").innerHTML='<b>Public shell:</b> ranked candidate search is withheld; this button recalls a frozen supported demonstration state.';$("supportWhy").textContent='Production search, ranking, support calibration and inverse optimization are protected.';draw()}
function surgName(v){return +v>=.85?'Gross / near-total':+v>=.30?'Partial resection':'Biopsy only'}
function labels(){$("vSurg").textContent=surgName(P.surg);$("vRt").textContent=P.rt.toFixed(1)+' Gy-eq';$("vTz").textContent=P.tz.toFixed(2);$("vWk").textContent='Week '+P.wk}
[['rt','rt'],['tz','tz'],['wk','wk']].forEach(([id,key])=>$(id).addEventListener('input',()=>{P[key]=+$ (id).value;labels();draw()}));$("surg").addEventListener('change',()=>{P.surg=+$("surg").value;labels();draw()});$("mgmt").addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;P.mg=b.dataset.v==='1';[...$("mgmt").children].forEach(c=>c.setAttribute('aria-pressed',c===b));draw()});$("abpMode").addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;mode=b.dataset.m;[...$("abpMode").children].forEach(c=>c.setAttribute('aria-pressed',c===b));$("abpModeTitle").textContent=mode[0].toUpperCase()+mode.slice(1);$("abpModeText").textContent=mode==='discovery'?'Interrogate the primitive against a declared target.':mode==='design'?'Compare frozen intervention constructions against the same displayed primitive.':'Expose context and response modifiers in the public shell.';$("designSection").style.display=mode==='design'?'block':'none';draw()});$("optimizeIntervention").addEventListener('click',applySupported);$("inverseObjective").addEventListener('change',()=>{$("bestRoute").textContent='Select OPTIMIZE INTERVENTION to recall the frozen supported state.'});$("opt").addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;$("inverseObjective").value=b.dataset.o==='rano'?'rano':'inf';applySupported();$("cmp").hidden=false;$("reveal").textContent='The public shell displays the response-versus-margin trade-off without distributing the protected objective function or search.'});
$("abpEvidence").addEventListener('change',()=>{const v=$("abpEvidence").value;if(v==='gbm'){evidenceTitle.textContent='Glioblastoma intervention design';evidenceText.textContent='Rotating literature-grounded visual demonstration of target-conditioned intervention states.'}if(v==='ohio'){evidenceTitle.textContent='Validated individual primitive · OhioT1DM';evidenceText.textContent='194,010 five-minute observations across 12 people underpin the principal individual-first validation; production primitive compilation is withheld.'}if(v==='nbl'){evidenceTitle.textContent='TARGET-NBL drug-regulator hypothesis screen';evidenceText.textContent='Public provenance context only; ranked drug-screening logic is withheld.'}});
cv.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY};spin=false;cv.setPointerCapture(e.pointerId)});cv.addEventListener('pointermove',e=>{if(!drag)return;rotY+=(e.clientX-drag.x)*.008;rotX=clamp(rotX+(e.clientY-drag.y)*.006,.04,1.15);drag={x:e.clientX,y:e.clientY};draw()});cv.addEventListener('pointerup',()=>{drag=null;spin=true});cv.addEventListener('pointercancel',()=>{drag=null;spin=true});cv.addEventListener('wheel',e=>{e.preventDefault();rotY+=Math.sign(e.deltaY)*.18;draw()},{passive:false});let last=0;function loop(ts){if(spin&&ts-last>60){rotY+=.006;draw();last=ts}requestAnimationFrame(loop)}
$("downloadReport").onclick=()=>{const body=`ABP public visual-shell report\n\n${$("bestRoute").textContent}\n${$("bestLevels").textContent}\n\n${$("contrastLine").textContent}\n\nNo production primitive compiler, response operator, candidate grid, support calibration or inverse optimizer is included in this public site.`;const b=new Blob([body],{type:'text/plain'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='ABP_public_visual_shell_report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)};
addEventListener('resize',()=>{size();draw()});size();labels();draw();requestAnimationFrame(loop);})();